// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format

import { defineConfig } from 'eslint/config';
import tsEslint from 'typescript-eslint';
import prettier from 'eslint-plugin-prettier/recommended';

export default defineConfig([
  {
    files: ['**/*.js', '**/*.mjs', '**/*.ts', '**/*.mts', '**/*.html'],
    extends: [prettier],
    rules: {
      'prettier/prettier': ['error'],
    },
  },
  {
    files: ['**/*.js', '**/*.mjs', '**/*.ts', '**/*.mts'],
    rules: {
      // Possible Problems
      'array-callback-return': ['error', { allowImplicit: true, checkForEach: true }],
      'constructor-super': ['error'],
      'for-direction': ['error'],
      'getter-return': ['error'],
      'no-async-promise-executor': ['error'],
      'no-await-in-loop': ['warn'],
      'no-class-assign': ['error'],
      'no-compare-neg-zero': ['error'],
      'no-cond-assign': ['error'],
      'no-const-assign': ['error'],
      'no-constant-binary-expression': ['error'],
      'no-constant-condition': ['error'],
      'no-constructor-return': ['warn'],
      'no-control-regex': ['error'],
      'no-debugger': ['error'],
      'no-dupe-args': ['error'],
      'no-dupe-class-members': ['error'],
      'no-dupe-else-if': ['error'],
      'no-dupe-keys': ['error'],
      'no-duplicate-case': ['error'],
      'no-duplicate-imports': ['off'],
      'no-empty-character-class': ['error'],
      'no-empty-pattern': ['error'],
      'no-ex-assign': ['error'],
      'no-fallthrough': ['error'],
      'no-func-assign': ['error'],
      'no-import-assign': ['error'],
      'no-inner-declarations': ['error'],
      'no-invalid-regexp': ['error'],
      'no-irregular-whitespace': ['error'],
      'no-loss-of-precision': ['error'],
      'no-misleading-character-class': ['error'],
      'no-new-native-nonconstructor': ['error'],
      'no-obj-calls': ['error'],
      'no-promise-executor-return': ['error'],
      'no-prototype-builtins': ['error'],
      'no-self-assign': ['error'],
      'no-self-compare': ['error'],
      'no-setter-return': ['error'],
      'no-sparse-arrays': ['error'],
      'no-template-curly-in-string': ['error'],
      'no-this-before-super': ['error'],
      'no-unassigned-vars': ['error'],
      'no-undef': ['error'],
      'no-unexpected-multiline': ['error'],
      'no-unmodified-loop-condition': ['warn'],
      'no-unreachable': ['error'],
      'no-unreachable-loop': ['error'],
      'no-unsafe-finally': ['error'],
      'no-unsafe-negation': ['error'],
      'no-unsafe-optional-chaining': ['error'],
      'no-unused-private-class-members': ['error'],
      'no-unused-vars': ['error'],
      'no-use-before-define': ['error'],
      'no-useless-assignment': ['error'],
      'no-useless-backreference': ['error'],
      'require-atomic-updates': ['error'],
      'use-isnan': ['error'],
      'valid-typeof': ['error'],

      // Suggestions
      'accessor-pairs': ['error'],
      'arrow-body-style': ['error'],
      'block-scoped-var': ['error'],
      camelcase: ['off'],
      'capitalized-comments': ['off'],
      'class-methods-use-this': ['warn'],
      complexity: ['warn', 20],
      'consistent-return': ['off'],
      'consistent-this': ['error'],
      curly: ['error', 'multi', 'consistent'],
      'default-case': ['off'],
      'default-case-last': ['off'],
      'default-param-last': ['error'],
      'dot-notation': ['error'],
      eqeqeq: ['error'],
      'func-name-matching': ['error'],
      'func-names': ['error', 'as-needed'],
      'func-style': ['error', 'declaration', { allowArrowFunctions: false }],
      'grouped-accessor-pairs': ['error'],
      'guard-for-in': ['error'],
      'id-denylist': ['off'],
      'id-length': ['off'],
      'id-match': ['off'],
      'init-declarations': ['error'],
      'logical-assignment-operators': ['error'],
      'max-classes-per-file': ['error'],
      'max-depth': ['warn', 4],
      'max-lines': ['warn', { max: 400, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['warn', { max: 75, skipBlankLines: true, skipComments: true, IIFEs: true }],
      'max-nested-callbacks': ['warn', { max: 4, checkConstructorCallCallbacks: true }],
      'max-params': ['warn', { max: 4, countThis: 'never' }],
      'max-statements': ['warn', { max: 20 }, { ignoreTopLevelFunctions: true }],
      'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: false }],
      'no-alert': ['error'],
      'no-array-constructor': ['error'],
      'no-bitwise': ['error'],
      'no-caller': ['error'],
      'no-case-declarations': ['error'],
      'no-console': ['warn'],
      'no-continue': ['off'],
      'no-delete-var': ['error'],
      'no-div-regex': ['error'],
      'no-else-return': ['error'],
      'no-empty': ['error'],
      'no-empty-function': ['error'],
      'no-empty-static-block': ['error'],
      'no-eq-null': ['error'],
      'no-eval': ['error'],
      'no-extend-native': ['error'],
      'no-extra-bind': ['error'],
      'no-extra-boolean-cast': ['error'],
      'no-extra-label': ['off'],
      'no-global-assign': ['error'],
      'no-implicit-coercion': ['error'],
      'no-implicit-globals': ['error'],
      'no-implied-eval': ['error'],
      'no-inline-comments': ['warn'],
      'no-invalid-this': ['error'],
      'no-iterator': ['error'],
      'no-label-var': ['off'],
      'no-labels': ['error'],
      'no-lone-blocks': ['error'],
      'no-lonely-if': ['error'],
      'no-loop-func': ['error'],
      'no-magic-numbers': ['off'],
      'no-multi-assign': ['error', { ignoreNonDeclaration: true }],
      'no-multi-str': ['error'],
      'no-negated-condition': ['off'],
      'no-nested-ternary': ['error'],
      'no-new': ['error'],
      'no-new-func': ['error'],
      'no-new-wrappers': ['error'],
      'no-nonoctal-decimal-escape': ['error'],
      'no-object-constructor': ['error'],
      'no-octal': ['error'],
      'no-octal-escape': ['error'],
      'no-param-reassign': ['error'],
      'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
      'no-proto': ['error'],
      'no-redeclare': ['error'],
      'no-regex-spaces': ['error'],
      'no-restricted-exports': ['off'],
      'no-restricted-globals': ['off'],
      'no-restricted-imports': ['off'],
      'no-restricted-properties': ['off'],
      'no-restricted-syntax': ['off'],
      'no-return-assign': ['error', 'always'],
      'no-script-url': ['error'],
      'no-sequences': ['error'],
      'no-shadow': ['error'],
      'no-shadow-restricted-names': ['error'],
      'no-ternary': ['off'],
      'no-throw-literal': ['error'],
      'no-undef-init': ['off'],
      'no-undefined': ['off'],
      'no-underscore-dangle': ['error'],
      'no-unneeded-ternary': ['error'],
      'no-unused-expressions': ['error'],
      'no-unused-labels': ['error'],
      'no-useless-call': ['error'],
      'no-useless-catch': ['error'],
      'no-useless-computed-key': ['error'],
      'no-useless-concat': ['error'],
      'no-useless-constructor': ['error'],
      'no-useless-escape': ['error'],
      'no-useless-rename': ['error'],
      'no-useless-return': ['error'],
      'no-var': ['error'],
      'no-void': ['error', { allowAsStatement: true }],
      'no-warning-comments': ['warn'],
      'no-with': ['error'],
      'object-shorthand': ['error'],
      'one-var': ['error', 'never'],
      'operator-assignment': ['error'],
      'prefer-arrow-callback': ['error'],
      'prefer-const': ['error', { destructuring: 'all' }],
      'prefer-destructuring': ['error'],
      'prefer-exponentiation-operator': ['error'],
      'prefer-named-capture-group': ['off'],
      'prefer-numeric-literals': ['error'],
      'prefer-object-has-own': ['error'],
      'prefer-object-spread': ['error'],
      'prefer-promise-reject-errors': ['error'],
      'prefer-regex-literals': ['off'],
      'prefer-rest-params': ['error'],
      'prefer-spread': ['error'],
      'prefer-template': ['error'],
      'preserve-caught-error': ['error'],
      radix: ['error'],
      'require-await': ['error'],
      'require-unicode-regexp': ['error'],
      'require-yield': ['error'],
      'sort-imports': ['off'],
      'sort-keys': ['off'],
      'sort-vars': ['off'],
      strict: ['error'],
      'symbol-description': ['error'],
      'vars-on-top': ['off'],
      yoda: ['error'],

      // Layout & Formatting
      'unicode-bom': ['off'],
    },
  },
  {
    files: ['**/*.ts', '**/*.mts'],
    languageOptions: {
      parser: tsEslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {},
  },
]);
